### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by CatoLeanTruetschel** [AI4E/AI4E.Memory.Compatibility#1]
Add support for (at least) the Span&lt;T&gt; and Memory&lt;T&gt; based APIs that are available in .Net Core but not .Net Standard.
The initial set of supported API is as described in https://github.com/dotnet/corefx/issues/21281.  

- [ ] System.BitConverter
- [ ] System.Convert
- [x] System.Random
- [ ] System.Int16
- [ ] System.DateTime
- [ ] System.DateTimeOffset
- [ ] System.TimeSpan
- [ ] System.Version
- [x] System.Guid
   - [x] Ctor _(implemented as a static Create method on the GuidHelper class)_
   - [x] TryWriteBytes
   - [x] static Parse _(implemented as a static method on the GuidHelper class)_
   - [x] static ParseExact _(implemented as a static method on the GuidHelper class)_
   - [x] static TryParse _(implemented as a static method on the GuidHelper class)_
   - [x] static TryParseExact _(implemented as a static method on the GuidHelper class)_
   - [x] TryFormat
- [ ] System.String
   - [x] Ctor _(implemented as a static Create method on the StringHelper class)_
   - [ ] static Create<TState> method
- [x] System.IO.Stream
   - [x] Read
   - [x] ReadAsync
   - [x] Write
   - [x] WriteAsync
- [ ] Sytem.IO.TextReder
- [ ] System.IO.TextWriter
- [ ] System.IO.BinaryReader
- [ ] System.IO.BinaryWriter
- [ ] System.Text.StringBuilder
- [ ] System.Text.Encoding
   - [x] GetByteCount
   - [x] TryGetBytes
   - [x] GetCharCount
   - [x] TryGetChars
   - [x] GetString
   - [ ] Preamble property
- [ ] System.Numerics.BigInteger
- [ ] System.Net.IPAddress
- [ ] System.Net.Sockets.Socket
- [ ] System.Net.Sockets.SocketTaskExtensions
- [ ] System.Net.WebSockets.WebSocket
- [ ] System.Net.Http.HttpClient
- [x] System.Security.Cryptography.HashAlgorithm
   - [x] TryComputeHash
- [ ] System.Security.Cryptography.IncrementalHash
- [ ] System.Security.Cryptography.RSA
- [ ] System.Security.Cryptography.DSA
- [ ] System.Security.Cryptography.ECDsa
